runtime: nodejs12
env: standard

manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
